// Bithumb symbol -> localized names mapping
// Note: Bithumb public API does not expose names with the ticker endpoint.
// Extend this list over time or generate from an admin script.

export const bithumbNames: Record<string, { english_name: string; korean_name: string }> = {
  BTC: { english_name: "Bitcoin", korean_name: "비트코인" },
  ETH: { english_name: "Ethereum", korean_name: "이더리움" },
  XRP: { english_name: "XRP", korean_name: "리플" },
  ADA: { english_name: "Cardano", korean_name: "에이다" },
  SOL: { english_name: "Solana", korean_name: "솔라나" },
  DOGE: { english_name: "Dogecoin", korean_name: "도지코인" },
  DOT: { english_name: "Polkadot", korean_name: "폴카닷" },
  TRX: { english_name: "TRON", korean_name: "트론" },
  LTC: { english_name: "Litecoin", korean_name: "라이트코인" },
  BCH: { english_name: "Bitcoin Cash", korean_name: "비트코인캐시" },
  EOS: { english_name: "EOS", korean_name: "이오스" },
  XLM: { english_name: "Stellar", korean_name: "스텔라루멘" },
  LINK: { english_name: "Chainlink", korean_name: "체인링크" },
  MATIC: { english_name: "Polygon", korean_name: "폴리곤" },
  SHIB: { english_name: "Shiba Inu", korean_name: "시바이누" },
  APT: { english_name: "Aptos", korean_name: "앱토스" },
  AVAX: { english_name: "Avalanche", korean_name: "아발란체" },
  NEAR: { english_name: "NEAR Protocol", korean_name: "니어프로토콜" },
  SAND: { english_name: "The Sandbox", korean_name: "더 샌드박스" },
  AXS: { english_name: "Axie Infinity", korean_name: "엑시인피니티" },
  FLOW: { english_name: "Flow", korean_name: "플로우" },
  GRT: { english_name: "The Graph", korean_name: "더 그래프" },
  AAVE: { english_name: "Aave", korean_name: "에이브" },
  UNI: { english_name: "Uniswap", korean_name: "유니스왑" },
  KNC: { english_name: "Kyber Network", korean_name: "카이버네트워크" },
  ICX: { english_name: "ICON", korean_name: "아이콘" },
  KLAY: { english_name: "Klaytn", korean_name: "클레이튼" },
  QTUM: { english_name: "Qtum", korean_name: "퀀텀" },
  ETC: { english_name: "Ethereum Classic", korean_name: "이더리움클래식" },
  XEM: { english_name: "NEM", korean_name: "넴" },
  XTZ: { english_name: "Tezos", korean_name: "테조스" },
  OMG: { english_name: "OMG Network", korean_name: "오미세고" },
  ZIL: { english_name: "Zilliqa", korean_name: "질리카" },
  IOST: { english_name: "IOST", korean_name: "아이오에스티" },
  IOTA: { english_name: "IOTA", korean_name: "아이오타" },
  SXP: { english_name: "Solar", korean_name: "솔라" },
  HIVE: { english_name: "Hive", korean_name: "하이브" },
  KAVA: { english_name: "Kava", korean_name: "카바" },
  LINK2: { english_name: "Chainlink", korean_name: "체인링크" },
};

