import { IFaqsLists, IScheduleData } from "../interface/iproject";

export async function fetchProjects() {
  const response = await fetch(
    `https://port-0-awwwards-ec2-server-eu1k2lllevrzc8.sel3.cloudtype.app/api/projects`
  );
  return await response.json();
}

export async function fetchVistited() {
  const response = await fetch(
    `https://port-0-awwwards-ec2-server-eu1k2lllevrzc8.sel3.cloudtype.app/api/visited`
  );
  return await response.json();
}

export const gameName: string[] = [
  "League of Legends",
  "War Thunder",
  "Black Desert",
];

export const faqList: IFaqsLists[] = [
  {
    q: "국비지원학원을 다니기 전엔 무엇을 하셧나요?",
    a: "다리 조인트 교체 및 설치 노동을 했습니다.",
  },
  {
    q: "국비지원학원을 다니게 된 계기가 있나요?",
    a:
      "효율적이고 빠르게 취업하고 싶어하는 저에게 군대 동기가 추천해주었습니다.",
  },
  {
    q: "대학을 안나온? 못나온? 이유가 있나요?",
    a:
      "대학을 나올정도의 성적은 되었지만 대학에 대해 굉장히 부정적이어서 가지 않았습니다.",
  },
  {
    q: "고졸 문제는 어떻게 해결하실 건가요?",
    a:
      "취업 후 제가 회사에 민폐 끼치질 않을 정도의 실력되면 사이버대학으로 졸업장을 취득할거같습니다.",
  },
  {
    q: "대학에 관심이 없었다면 왜 특성화고에 가지 않았나요?",
    a:
      "부모님의 반대가 매우 심했습니다. 개발자라는 직업도 마찬가지 였지만 지금은 설득에 성공했습니다.",
  },
  {
    q: "국비지원학원 끝난지가 좀 됐는데 왜 지금 구직활동을 하시나요?",
    a:
      "부정교합으로 인한 수술이 국비지원학원 수료후에 바로 예정되어있었고, 회복기간까지 필요하다보니 이제서야 하게 됐네요. +프론트공부",
  },
  {
    q: "프론트엔드에 개발자가 되기로 마음먹은 이유가 있나요?",
    a:
      "팀 프로젝트를 진행하며 백, 프론트 둘다 해보니 프론트엔드 쪽이 백엔드보다 잘맞는거같았고 더 재밋다고 느껴서 마음 먹었습니다. 하지만 풀스택을 목표로 하고 있습니다.",
  },
  {
    q: "사용할줄 아는 언어, 라이브러리, 프레임워크는 뭔가요?",
    a:
      "javascript, jquery, react, typescript가 있습니다. 지금은 nextjs를 공부중에 있습니다.",
  },
  {
    q: "java, spring, python, DB도 배웠다던데 사용 할줄 아시나요?",
    a: "프로젝트에서 조금이나마 사용은 해봤지만 지금은 다시 공부해야 합니다.",
  },
];

export const schedule: IScheduleData[] = [
  {
    id: 0,
    text: [
      "Academy Project",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Institution training & Team Project",
    date: "2022. 04 ~ 2022. 09",
  },
  {
    id: 1,
    text: [
      "Surgery & Recovery",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Surgery & Recovery",
    date: "2022. 09 ~ 2022. 12",
  },
  {
    id: 2,
    text: [
      "My app",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Project",
    date: "2022. 11 ~ 2022. 12",
  },
  {
    id: 3,
    text: [
      "CRYPTO Tracker",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Project",
    date: "2022. 12 ~ 2023. 01",
  },
  {
    id: 4,
    text: [
      "KANBAN Borad",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Project",
    date: "2023. 01 ~ 2023. 02",
  },
  {
    id: 5,
    text: [
      "awwwards",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Project creation and maintenance",
    date: "2023. 02 ~ 2023. 06",
  },
  {
    id: 6,
    text: [
      "JavaScript",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "study",
    date: "2023. 03 ~ 2023. 04",
  },
  {
    id: 7,
    text: [
      "Node.js",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "study",
    date: "2023. 04 ~ 2023. 05",
  },
  {
    id: 8,
    text: [
      "Computer Science",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "study",
    date: "2023. 04 ~ 2023. 05",
  },
  {
    id: 9,
    text: [
      "Next.js, CarrotMarket",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Study and project",
    date: "2023. 07 ~ 2023. 10",
  },
  {
    id: 10,
    text: [
      "VisualCoin project",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox: "Discontinued due to cost issues",
    date: "2023. 06 ~ 2023. 08",
  },
  {
    id: 11,
    text: [
      "Project House",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox:
      "The team project is in progress (Based on scheduled end date)",
    date: "2023. 09 ~ ",
  },
  {
    id: 12,
    text: [
      "PRE-ONBOARDING (FE)",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    absoluteBox:
      "Wanted Challenge",
    date: "2023. 09 ~ ",
  },
  {
    id: 13,
    text: [
      "",
      "2022. 6",
      "2022. 7",
      "2022. 8",
      "2022. 9",
      "2022. 10",
      "2022. 11",
      "2022. 12",
      "2023. 1",
      "2023. 2",
      "2023. 3",
      "2023. 4",
      "2023. 5",
      "2023. 6",
      "2023. 7",
      "2023. 8",
      "2023. 9",
      "2023. 10",
      "2023. 11",
      "2023. 12",
    ],
    absoluteBox: "",
    date: "",
  },
];
